- hosts: at1
  vars:
    users:
      - sansa
      - jaime
      - robert
  tasks:
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present

    - name: create users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop: "{{ users }}"

    - name: add gitconfig
      ansible.builtin.template:
        src: templates/gitconfig.j2
        dest: "/home/{{ item }}/.gitconfig"
      loop: "{{ users }}"

    - name: create dir
      ansible.builtin.file:
        path: "/home/{{ item }}/.ssh"
        state: directory
      loop: "{{ users }}"

    - name: add ssh key
      ansible.builtin.copy:
        src: files/id_rsa.pub
        dest: "/home/{{ item }}/.ssh/authorized_keys"
      loop: "{{users}}"
